"""1st migration

Revision ID: 2baa20fdffd6
Revises: 
Create Date: 2025-06-09 10:36:43.805135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2baa20fdffd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=13), nullable=False),
    sa.Column('national_identity_number', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('national_identity_number'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('national_identity_number', sa.String(length=9), nullable=False),
    sa.Column('personnel_type', sa.Enum('Professional', 'Skilled', 'Unskilled'), nullable=False),
    sa.Column('wages', sa.Float(), nullable=False),
    sa.Column('role', sa.Enum('Project Manager', 'Architect', 'Structural Engineer', 'Quantity Surveyor', 'Mechanical Engineer', 'Electrical Engineer', 'Site Supervisor', 'Mason', 'Plumber', 'Electrician', 'Carpenter', 'Welder', 'Painter', 'Roofer', 'Laborer'), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('national_identity_number')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=13), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Pending', 'Suspended'), nullable=False),
    sa.Column('remaining_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('certification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Expired', 'Revoked', 'Pending'), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('date_bought', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'In Repair', 'Retired'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('Available', 'Not Available'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'In progress', 'Completed', 'On hold', 'Cancelled'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('financial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('financial_type', sa.Enum('Personnel Wages', 'Supplier Payments', 'Client Payments'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial')
    op.drop_table('project')
    op.drop_table('material')
    op.drop_table('equipment')
    op.drop_table('certification')
    op.drop_table('supplier')
    op.drop_table('personnel')
    op.drop_table('client')
    # ### end Alembic commands ###
